"""empty message

Revision ID: cfb440e34135
Revises: 
Create Date: 2024-07-29 09:40:51.820469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb440e34135'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rate', sa.Double(), server_default='1.0', nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies')),
    sa.UniqueConstraint('code', name=op.f('uq_currencies_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('passwd_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='basic', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('foreign_amounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Double(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_foreign_amounts_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foreign_amounts'))
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Double(), server_default='0.0', nullable=False),
    sa.Column('foreign_amount_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_expenses_category_id_categories')),
    sa.ForeignKeyConstraint(['foreign_amount_id'], ['foreign_amounts.id'], name=op.f('fk_expenses_foreign_amount_id_foreign_amounts')),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name=op.f('fk_expenses_payer_id_users')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_expenses_reporter_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('foreign_amounts')
    op.drop_table('users')
    op.drop_table('currencies')
    op.drop_table('categories')
    # ### end Alembic commands ###
